# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7387f1c489cf0a04013fe9dae935e376c0118b7dbc71257742a5e514659d2372ab82e185594c9acdd04567374877ecc829da6ff7cac1c0b458ea8b44f04679f0

test:
  secret_key_base: f296d86b8ed798c82974ba3814d808218cac1410396993255a1795ea5ea2ea0b46ac1892716d36e95a051b2013ff95fdb8442d89a4084810586bb7c3fb03b552

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
